/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:27.820
 */
package ca.cqdg.etl.validation.preprocess


case class BiospecimenExpected(`study_id`: String = "ST0001",
                               `submitter_donor_id`: String = "PT00001",
                               `submitter_biospecimen_id`: String = "BS00001",
                               `submitter_diagnosis_id`: String = "DI00001",
                               `date_biospecimen_collection`: String = "11/22/2009",
                               `tumor_normal_designation`: String = "Normal",
                               `biospecimen_tissue_source`: String = "Blood derived - peripheral blood",
                               `biospecimen_type`: String = "Normal",
                               `biospecimen_anatomic_location`: String = "C42.0",
                               `tumor_histological_type`: Option[String] = None,
                               `biospecimen_processing`: String = "Cryopreservation - other",
                               `biospecimen_storage`: String = "Frozen in -70 freezer",
                               `biospecimen_access`: String = "TRUE",
                               `internal_biospecimen_id`: String = "biospecimen_internal_id_1")

