/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:27.085
 */
package ca.cqdg.etl.validation.preprocess


case class DiagnosisExpected(`study_id`: String = "ST0001",
                             `submitter_donor_id`: String = "PT00001",
                             `submitter_diagnosis_id`: String = "DI00001",
                             `diagnosis_source_text`: String = "Heart attack",
                             `diagnosis_ICD_code`: String = "I21",
                             `diagnosis_mondo_code`: String = "MONDO:0005068",
                             `age_at_diagnosis`: String = "54",
                             `is_self_reported`: String = "TRUE",
                             `is_cancer`: String = "FALSE",
                             `is_cancer_primary`: Option[String] = None,
                             `diagnosis_type`: String = "Clinical",
                             `tumor_staging_system`: Option[String] = None,
                             `stage_group`: Option[String] = None,
                             `t_category`: Option[String] = None,
                             `n_category`: Option[String] = None,
                             `m_category`: Option[String] = None,
                             `internal_diagnosis_id`: String = "diagnosis_internal_id_1")

