/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:27.419
 */
package ca.cqdg.etl.validation.preprocess


case class DonorExpected(`study_id`: String = "ST0001",
                         `submitter_donor_id`: String = "PT00001",
                         `dob`: String = "6/9/1946",
                         `date_of_recruitment`: String = "11/22/2009",
                         `gender`: String = "Male",
                         `ethnicity`: String = "French Canadian ",
                         `vital_status`: String = "alive",
                         `cause_of_death`: Option[String] = None,
                         `age_of_death`: Option[String] = None,
                         `physical_measures_available`: String = "TRUE",
                         `laboratory_measures_available`: String = "FALSE",
                         `lifestyle_available`: String = "TRUE",
                         `medication_available`: String = "TRUE",
                         `environment_exposure_available`: String = "FALSE",
                         `family_history_available`: String = "TRUE",
                         `genealogy_available`: String = "FALSE",
                         `is_a_proband`: String = "Not applicable",
                         `is_affected`: String = "Not applicable",
                         `internal_donor_id`: String = "donor_internal_id_1")

