/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:27.973
 */
package ca.cqdg.etl.validation.preprocess


case class ExposureExpected(`study_id`: String = "ST0001",
                            `submitter_donor_id`: String = "PT00001",
                            `smoking_status`: String = "Never smoker        ",
                            `smoking_pack_years`: Option[String] = None,
                            `alcohol_status`: String = "No alcohol consumtion",
                            `FSA`: String = "J7C",
                            `internal_exposure_id`: String = "exposure_internal_id_1")

