/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:28.185
 */
package ca.cqdg.etl.validation.preprocess


case class FamilyhistoryExpected(`study_id`: String = "ST0001",
                                 `submitter_donor_id`: String = "PT00001",
                                 `submitter_family_condition_id`: String = "FC00001",
                                 `family_condition_name`: String = "Brain cancer",
                                 `family_condition_age`: String = "20",
                                 `family_condition_relationship`: String = "granddaughter",
                                 `family_cancer_history`: String = "Yes",
                                 `internal_familyhistory_id`: String = "family_history_internal_id_1")

