/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:29.060
 */
package ca.cqdg.etl.validation.preprocess


case class FamilyExpected(`study_id`: String = "ST0001",
                          `submitter_family_id`: String = "FA0001",
                          `submitter_donor_id`: String = "PT00001",
                          `family_type`: String = "Case-parent trio",
                          `is_a_proband`: String = "Is a proband",
                          `relationship_to_proband`: String = "Is the proband",
                          `internal_family_id`: String = "family_internal_id_1")

