/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:28.312
 */
package ca.cqdg.etl.validation.preprocess


case class FileExpected(`submitter_biospecimen_id`: String = "BS00001",
                        `submitter_donor_id`: String = "PT00001",
                        `study_id`: String = "ST0001",
                        `file_name`: String = "AOvTmom62.gvcf",
                        `data_category`: String = "Simple nucleotide variation",
                        `data_type`: String = "Raw SNV calls",
                        `is_harmonized`: String = "TRUE",
                        `experimental_strategy`: String = "WGS",
                        `data_access`: String = "Controled",
                        `file_format`: String = "gvcf",
                        `platform`: String = "Illumina",
                        `variant_class`: String = "Germline",
                        `internal_file_id`: String = "file_internal_id_1")

