/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:26.927
 */
package ca.cqdg.etl.validation.preprocess


case class FollowupExpected(`study_id`: String = "ST0001",
                            `submitter_donor_id`: String = "PT00001",
                            `submitter_diagnosis_id`: String = "DI00001",
                            `submitter_follow_up_id`: String = "FU00001",
                            `disease_status_at_followup`: String = "No evidence of disease",
                            `relapse_interval`: Option[String] = None,
                            `internal_followup_id`: String = "follow_up_internal_id_1")

