/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:28.896
 */
package ca.cqdg.etl.validation.preprocess


case class PhenotypeExpected(`study_id`: String = "ST0001",
                             `submitter_donor_id`: String = "PT00001",
                             `submitter_phenotype_id`: String = "PH00001",
                             `phenotype_source_text`: String = " Myocardial infarction",
                             `phenotype_HPO_code`: String = "HP:0001658",
                             `age_at_phenotype`: String = "63",
                             `phenotype_severity`: String = "Mild",
                             `phenotype_observed`: String = "TRUE",
                             `internal_phenotype_id`: String = "phenotype_internal_id_1")

