/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:29.458
 */
package ca.cqdg.etl.validation.preprocess


case class SampleregistrationExpected(`study_id`: String = "ST0001",
                                      `submitter_donor_id`: String = "PT00001",
                                      `submitter_biospecimen_id`: String = "BS00001",
                                      `submitter_sample_id`: String = "SA00001",
                                      `sample_type`: String = "Total DNA",
                                      `internal_sampleregistration_id`: String = "sample_registration_internal_id_1")

