/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:29.282
 */
package ca.cqdg.etl.validation.preprocess


case class StudyExpected(`study_id`: String = "ST0001",
                         `name`: String = "Study1",
                         `short_name`: String = "ST1",
                         `description`: String = "population-based cohort focusing on complex conditions",
                         `keyword`: String = "Common chronic disorders; Prospective cohort; Reference genome",
                         `access_authority`: String = "www.study1.ca",
                         `domain`: String = "General Health",
                         `population`: String = "Adult",
                         `access_limitations`: String = "DUO:0000005",
                         `access_requirements`: String = "DUO:0000017; DUO:0000024; DUO:0000026",
                         `internal_study_id`: String = "study_internal_id_1",
                         `dictionary_version`: String = "5.58",
                         `study_version`: String = "1.0",
                         `study_version_creation_date`: String = "2020/07/01")

