/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-24T17:36:27.599
 */
package ca.cqdg.etl.validation.preprocess


case class TreatmentExpected(`study_id`: String = "ST0001",
                             `submitter_donor_id`: String = "PT00001",
                             `submitter_treatment_id`: String = "TX00001",
                             `submitter_diagnosis_id`: String = "DI00001",
                             `treatment_type`: String = "Surgery",
                             `treatment_is_primary`: String = "Yes",
                             `treatment_intent`: String = "Curative",
                             `treatment_response`: String = "Not applicable",
                             `medication_name`: Option[String] = None,
                             `medication_code`: Option[String] = None,
                             `medication_class`: Option[String] = None,
                             `treatment_end_date`: Option[String] = None,
                             `internal_treatment_id`: String = "treatment_internal_id_1")

