/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:06.675961
 */
package ca.cqdg.etl.testutils.model


case class BiospecimenInput(`study_id`: String = "ST0001",
                            `submitter_donor_id`: String = "PT00001",
                            `submitter_biospecimen_id`: String = "BS00001",
                            `submitter_diagnosis_id`: String = "DI00001",
                            `date_biospecimen_collection`: String = "11/22/2009",
                            `tumor_normal_designation`: String = "Normal",
                            `biospecimen_tissue_source`: String = "Blood derived - peripheral blood",
                            `biospecimen_type`: String = "Normal",
                            `is_cancer`: String = "No",
                            `biospecimen_anatomic_location`: String = "C42.0: Blood",
                            `tumor_histological_type`: Option[String] = None,
                            `diagnosis_ICD_term`: String = "Acute myocardial infarction",
                            `biospecimen_processing`: String = "Cryopreservation - other",
                            `biospecimen_storage`: String = "Frozen in -70 freezer",
                            `biospecimen_access`: String = "Yes")

