/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-21T07:38:57.866558
 */
package ca.cqdg.etl.testutils.model


case class BiospecimenOutput(`submitter_biospecimen_id`: String = "BS00001",
                             `biospecimen`: List[BIOSPECIMEN] = List(BIOSPECIMEN()))

case class BIOSPECIMEN(`submitter_biospecimen_id`: String = "BS00001",
                       `submitter_diagnosis_id`: String = "DI00001",
                       `date_biospecimen_collection`: String = "11/22/2009",
                       `tumor_normal_designation`: String = "Normal",
                       `is_cancer`: String = "No",
                       `tumor_histological_type`: Option[String] = None,
                       `diagnosis_ICD_term`: String = "Acute myocardial infarction",
                       `biospecimen_processing`: String = "Cryopreservation - other",
                       `biospecimen_storage`: String = "Frozen in -70 freezer",
                       `biospecimen_access`: String = "Yes",
                       `tissue_source`: String = "Blood derived - peripheral blood",
                       `type`: String = "Normal",
                       `anatomic_location`: String = "C42.0: Blood",
                       `samples`: List[SAMPLES] = List(SAMPLES()))

case class SAMPLES(`submitter_sample_id`: String = "SA00001",
                   `sample_type`: String = "Total DNA")
