/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:07.447635
 */
package ca.cqdg.etl.testutils.model


case class DiagnosisInput(`submitter_diagnosis_id`: String = "DI00453",
                          `submitter_donor_id`: String = "PT00453",
                          `study_id`: String = "ST0002",
                          `diagnosis_type`: String = "Clinical",
                          `submitter_biospecimen_id`: Option[String] = None,
                          `diagnosis_source_text`: String = "Lip cancer",
                          `diagnosis_ICD_category`: String = "Neoplasms",
                          `diagnosis_ICD_term`: String = "C00: Malignant neoplasm of lip",
                          `diagnosis_mondo_term`: String = "MONDO_0006834: Lip cancer",
                          `age_at_diagnosis`: Int = 3,
                          `is_self_reported`: String = "No",
                          `is_cancer`: String = "Yes",
                          `is_cancer_primary`: String = "Yes",
                          `tumor_staging_system`: String = "AJCC 8th edition",
                          `stage_group`: String = "stage ia1",
                          `t_category`: String = "T1c",
                          `n_category`: String = "N1mi",
                          `m_category`: String = "M1d(0)")

