/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:30.918845
 */
package ca.cqdg.etl.testutils.model


case class DiagnosisInput(`submitter_diagnosis_id`: String = "DI00627",
                          `submitter_donor_id`: String = "PT00627",
                          `study_id`: String = "ST0003",
                          `diagnosis_type`: Option[String] = None,
                          `submitter_biospecimen_id`: Option[String] = None,
                          `diagnosis_source_text`: Option[String] = None,
                          `diagnosis_ICD_category`: Option[String] = None,
                          `diagnosis_ICD_term`: Option[String] = None,
                          `diagnosis_mondo_term`: Option[String] = None,
                          `age_at_diagnosis`: Option[String] = None,
                          `is_self_reported`: Option[String] = None,
                          `is_cancer`: Option[String] = None,
                          `is_cancer_primary`: Option[String] = None,
                          `tumor_staging_system`: Option[String] = None,
                          `stage_group`: Option[String] = None,
                          `t_category`: Option[String] = None,
                          `n_category`: Option[String] = None,
                          `m_category`: Option[String] = None)

