/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:31.270119
 */
package ca.cqdg.etl.testutils.model


case class DonorInput(`study_id`: String = "ST0001",
                      `submitter_donor_id`: String = "PT00001",
                      `submitter_family_id`: Option[String] = None,
                      `dob`: String = "6/9/1946",
                      `date_of_recruitment`: String = "11/22/2009",
                      `age_at_diagnosis`: String = "58",
                      `gender`: String = "Male",
                      `ethnicity`: String = "French Canadian ",
                      `vital_status`: String = "alive",
                      `cause_of_death`: Option[String] = None,
                      `age_of_death`: Option[String] = None,
                      `height`: String = "168",
                      `body_weight`: String = "85",
                      `bmi`: String = "30.12",
                      `physical_measures_available`: String = "YES",
                      `laboratory_measures_available`: String = "NO",
                      `lifestyle_available`: String = "YES",
                      `medication_available`: String = "YES",
                      `environment_exposure_available`: String = "NO",
                      `family_history_available`: String = "YES",
                      `genealogy_available`: String = "NO",
                      `is_a_proband`: String = "Not applicable",
                      `is_affected`: String = "Not applicable",
                      `seq`: String = "1",
                      `snv`: String = "1",
                      `cnv`: Option[String] = None,
                      `sv`: Option[String] = None,
                      `exp`: Option[String] = None,
                      `meth`: Option[String] = None)

