/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:54:33.442292
 */
package ca.cqdg.etl.testutils.model


case class DonorDiagnosisOutput(`submitter_donor_id`: String = "PT00453",
                                `study_id`: String = "ST0002",
                                `diagnosis_per_donor_per_study`: List[DONOR_DIAGNOSIS_PER_DONOR_PER_STUDY] = List(DONOR_DIAGNOSIS_PER_DONOR_PER_STUDY()))

case class DONOR_DIAGNOSIS_PER_DONOR_PER_STUDY(`submitter_diagnosis_id`: String = "DI00453",
                                               `diagnosis_type`: String = "Clinical",
                                               `submitter_biospecimen_id`: Option[String] = None,
                                               `diagnosis_source_text`: String = "Lip cancer",
                                               `diagnosis_ICD_category`: String = "Neoplasms",
                                               `diagnosis_ICD_term`: String = "C00: Malignant neoplasm of lip",
                                               `diagnosis_mondo_term`: String = "MONDO_0006834: Lip cancer",
                                               `age_at_diagnosis`: Int = 3,
                                               `is_self_reported`: String = "No",
                                               `is_cancer`: Boolean = true,
                                               `is_cancer_primary`: String = "Yes",
                                               `tumor_staging_system`: String = "AJCC 8th edition",
                                               `stage_group`: String = "stage ia1",
                                               `t_category`: String = "T1c",
                                               `n_category`: String = "N1mi",
                                               `m_category`: String = "M1d(0)",
                                               `treatments`: List[DIAGNOSIS_TREATMENTS] = List(DIAGNOSIS_TREATMENTS()),
                                               `follow_ups`: List[DIAGNOSIS_FOLLOW_UPS] = List(DIAGNOSIS_FOLLOW_UPS()))

case class DIAGNOSIS_TREATMENTS(`submitter_treatment_id`: String = "TX00001",
                                `treatment_type`: String = "Surgery",
                                `treatment_is_primary`: String = "Yes",
                                `treatment_intent`: String = "Curative",
                                `treatment_response`: String = "Not applicable",
                                `medication_name`: Option[String] = None,
                                `medication_code`: Option[String] = None,
                                `medication_class`: Option[String] = None,
                                `medication_start_date`: Option[String] = None,
                                `medication_end_date`: Option[String] = None)

case class DIAGNOSIS_FOLLOW_UPS(`submitter_follow_up_id`: String = "FU00002",
                                `days_to_follow_up`: Int = 68,
                                `disease_status_at_followup`: String = "No evidence of disease",
                                `relapse_interval`: Option[Int] = None,
                                `treatment_response`: String = "Disease Progression")
