/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T16:19:32.132020
 */
package ca.cqdg.etl.testutils.model


case class DonorOutput(`age_at_recruitment`: String = "57",
                       `date_of_recruitment`: String = "5/10/2009",
                       `diagnoses`: List[DONOR_DIAGNOSES] = List(DONOR_DIAGNOSES()),
                       `dob`: String = "2/21/1951",
                       `environment_exposure_available`: String = "NO",
                       `ethnicity`: String = "French Canadian ",
                       `exposure`: List[EXPOSURE] = List(EXPOSURE()),
                       `exposures`: List[EXPOSURE] = List(EXPOSURE()), // ???????????
                       `familyConditions`: List[FAMILYCONDITIONS] = List(FAMILYCONDITIONS()),
                       `familyHistory`: List[FAMILYHISTORY] = List(FAMILYHISTORY()),
                       `family_history_available`: String = "NO",
                       `files`: List[FILES] = List(FILES()),
                       `gender`: String = "Female",
                       `genealogy_available`: String = "YES",
                       `is_a_proband`: String = "Not applicable",
                       `is_affected`: String = "Not applicable",
                       `laboratory_measures_available`: String = "NO",
                       `lifestyle_available`: String = "NO",
                       `medication_available`: String = "YES",
                       `phenotypes`: List[PHENOTYPES] = List(PHENOTYPES()),
                       `physical_measures_available`: String = "NO",
                       `study`: List[STUDY] = List(STUDY()),
                       `submitter_donor_id`: String = "PT00060",
                       `vital_status`: String = "alive")

case class STUDY(`description`: String = "population-based cohort focusing on complex conditions",
                 `domain`: String = "General Health",
                 `keyword`: String = "Common chronic disorders; Prospective cohort; Reference genome",
                 `name`: String = "Study1",
                 `population`: String = "Adult",
                 `short_name`: String = "ST1",
                 `short_name_keyword`: String = "ST1",
                 `short_name_ngrams`: String = "ST1",
                 `study_id`: String = "ST0001",
                 `study_id_keyword`: String = "ST0001")

case class FAMILYHISTORY(`family_cancer_history`: String = "Yes",
                         `family_condition_age`: Long = 48,
                         `family_condition_name`: String = "Multiple sclerosis",
                         `family_condition_relationship`: String = "maternal aunt",
                         `submitter_family_condition_id`: String = "FC00060")

case class DONOR_DIAGNOSES(`age_at_diagnosis`: Long = 52,
                     `diagnosis_type`: String = "Clinical",
                     `follow_ups`: List[FOLLOW_UPS] = List(FOLLOW_UPS()),
                     `is_cancer`: Boolean = true,
                     `is_cancer_primary`: String = "Yes",
                     `is_self_reported`: String = "Yes",
                     `m_category`: String = "M1d(0)",
                     `n_category`: String = "N2",
                     `stage_group`: String = "stage iia",
                     `submitter_diagnosis_id`: String = "DI00060",
                     `t_category`: String = "Tis(LCIS)",
                     `treatments`: List[TREATMENTS] = List(TREATMENTS()))

case class FOLLOW_UPS(`days_to_follow_up`: Long = 81,
                      `disease_status_at_followup`: String = "Stable",
                      `submitter_follow_up_id`: String = "FU00060")

case class FILES(`data_access`: String = "Controled",
                 `data_category`: String = "Sequencing reads",
                 `data_type`: String = "Aligned reads",
                 `experimental_strategy`: String = "WGS",
                 `file_format`: String = "cram",
                 `file_name`: String = "uK9WHQ0.cram",
                 `file_name_keyword`: String = "uK9WHQ0.cram",
                 `file_name_ngrams`: String = "uK9WHQ0.cram",
                 `file_size`: Double = 13.02056279174796,
                 `file_variant_class`: Option[String] = None,
                 `is_harmonized`: Boolean = true,
                 `platform`: String = "Illumina",
                 `submitter_biospecimen_id`: String = "BS00060")

case class EXPOSURE(`FSA`: String = "H4V",
                    `alcohol_status`: String = "Alcohol consumption unknown",
                    `smoking_status`: String = "Current every day smoker        ")
