/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:31.540973
 */
package ca.cqdg.etl.testutils.model


case class ExposureInput(`study_id`: String = "ST0001",
                         `submitter_donor_id`: String = "PT00001",
                         `submitter_exposure_id`: String = "EX00001",
                         `smoking_status`: String = "Never smoker        ",
                         `alcohol_status`: String = "No alcohol consumtion",
                         `FSA`: String = "J7C")

