/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:08.812096
 */
package ca.cqdg.etl.testutils.model


case class FamilyInput(`submitter_family_id`: String = "FA0001",
                       `submitter_donor_id`: String = "PT00627",
                       `family_type`: String = "Case-parent trio",
                       `study_id`: String = "ST0003",
                       `relationship_to_proband`: String = "Wife",
                       `gender`: String = "Female")

