/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:31.965368
 */
package ca.cqdg.etl.testutils.model


case class FamilyRelationshipInput(`submitter_family_id`: String = "FA0001",
                                   `submitter_donor_id_1`: String = "PT00627",
                                   `submitter_donor_id_2`: String = "PT00628",
                                   `family_type`: String = "Case-parent trio",
                                   `study_id`: String = "ST0003",
                                   `familiy_1_2_relationship`: String = "Wife",
                                   `family_2_1_relationship`: String = "Husband",
                                   `gender`: String = "Female")

