/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:31.758515
 */
package ca.cqdg.etl.testutils.model


case class FamilyHistoryInput(`study_id`: String = "ST0001",
                              `submitter_donor_id`: String = "PT00001",
                              `submitter_family_condition_id`: String = "FC00001",
                              `family_condition_name`: String = "Brain cancer",
                              `family_condition_age`: String = "20",
                              `family_condition_relationship`: String = "granddaughter",
                              `family_cancer_history`: String = "No",
                              `age TODAY`: String = "74")

