/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:09.119359
 */
package ca.cqdg.etl.testutils.model


case class FileInput(`submitter_biospecimen_id`: Option[String] = None,
                     `submitter_donor_id`: String = "PT00627",
                     `study_id`: String = "ST0003",
                     `file_name`: String = "zplTjYga3.pdf",
                     `data_category`: String = "Clinical",
                     `data_type`: String = "Pathological report",
                     `is_harmonized`: Boolean = false,
                     `experimental_strategy`: Option[String] = None,
                     `data_access`: String = "Controled",
                     `file_format`: String = "pdf",
                     `platform`: Option[String] = None,
                     `variant_class`: Option[String] = None)

