/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:37:32.435326
 */
package ca.cqdg.etl.testutils.model


case class FollowUpInput(`submitter_follow_up_id`: String = "FU00002",
                         `submitter_donor_id`: String = "PT00002",
                         `study_id`: String = "ST0001",
                         `submitter_diagnosis_id`: String = "DI00002",
                         `days_to_follow_up`: String = "68",
                         `disease_status_at_followup`: String = "No evidence of disease",
                         `relapse_interval`: Option[String] = None,
                         `treatment_response`: String = "Disease Progression",
                         `is_cancer`: String = "Yes")

