/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-25T13:22:13.987266
 */
package ca.cqdg.etl.testutils.model


case class HpoTermsInput(`ancestors`: List[ANCESTORS] = List(ANCESTORS()),
                         `id`: String = "HP:0001694",
                         `is_leaf`: Boolean = true,
                         `name`: String = "Right-to-left shunt",
                         `parents`: List[String] = List("Cardiac shunt (HP:0001693)"))

case class ANCESTORS(`id`: String = "HP:0001626",
                     `name`: String = "Abnormality of the cardiovascular system",
                     `parents`: List[String] = List("Phenotypic abnormality (HP:0000118)"))
