/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-25T13:22:16.132895
 */
package ca.cqdg.etl.testutils.model


case class MondoTermsInput(`ancestors`: List[ANCESTORS] = List(ANCESTORS(`id` = "MONDO:0005070", `name` = "neoplasm (disease)", `parents` = List("neoplastic disease or syndrome (MONDO:0023370)"))),
                           `id`: String = "MONDO:0015341",
                           `is_leaf`: Boolean = true,
                           `name`: String = "congenital panfollicular nevus (disease)",
                           `parents`: List[String] = List("melanocytic nevus (MONDO:0005073)"))
