/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:09.651180
 */
package ca.cqdg.etl.testutils.model


case class PhenotypeInput(`study_id`: String = "ST0001",
                          `submitter_donor_id`: String = "PT00001",
                          `submitter_phenotype_id`: String = "PH00001",
                          `phenotype_HPO_code`: String = "HP:0001658",
                          `phenotype_HPO_term`: String = " Myocardial infarction",
                          `phenotype_HPO_category`: String = "Abnormality of the cardiovascular system",
                          `age_at_phenotype`: Int = 63,
                          `phenotype_observed`: String = "Yes")

