/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-21T07:54:12.454364
 */
package ca.cqdg.etl.testutils.model


case class PhenotypeOutput(`submitter_donor_id`: String = "PT00001",
                           `study_id`: String = "ST0001",
                           `phenotypes_per_donor_per_study`: List[PHENOTYPES_PER_DONOR_PER_STUDY] = List(PHENOTYPES_PER_DONOR_PER_STUDY()))

case class PHENOTYPES_PER_DONOR_PER_STUDY(`submitter_phenotype_id`: String = "PH00001",
                                          `phenotype_HPO_term`: String = " Myocardial infarction",
                                          `phenotype_HPO_category`: String = "Abnormality of the cardiovascular system",
                                          `age_at_phenotype`: Int = 63,
                                          `hpo_code`: String = "HP:0001658")
