/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:09.891884
 */
package ca.cqdg.etl.testutils.model


case class SampleRegistrationInput(`study_id`: String = "ST0001",
                                   `submitter_donor_id`: String = "PT00001",
                                   `submitter_biospecimen_id`: String = "BS00001",
                                   `submitter_sample_id`: String = "SA00001",
                                   `sample_type`: String = "Total DNA")

