/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-18T12:38:29.271717
 */
package ca.cqdg.etl.testutils.model


case class StudyInput(`study_id`: String = "ST0001",
                      `name`: String = "Study1",
                      `short_name`: String = "ST1",
                      `description`: String = "population-based cohort focusing on complex conditions",
                      `keyword`: String = "Common chronic disorders; Prospective cohort; Reference genome",
                      `website`: String = "www.study1.ca",
                      `domain`: String = "General Health",
                      `population`: String = "Adult",
                      `access_limitations`: String = "General research use and clinical care (DUO_0000005)",
                      `access_requirements`: String = "Ethics approval required (DUO:0000021); Time limit on use (DUO:0000025)",
                      `nb_donors`: String = "377",
                      `nb_files`: String = "754",
                      `seq`: String = "555",
                      `snv`: String = "0",
                      `cnv`: String = "0",
                      `sv`: String = "0",
                      `exp`: String = "0",
                      `meth`: String = "0")

