/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-05-20T16:53:10.374367
 */
package ca.cqdg.etl.testutils.model


case class TreatmentInput(`submitter_treatment_id`: String = "TX00001",
                          `submitter_donor_id`: String = "PT00001",
                          `study_id`: String = "ST0001",
                          `submitter_diagnosis_id`: String = "DI00001",
                          `treatment_type`: String = "Surgery",
                          `diagnosis_ICD_term`: String = "Acute myocardial infarction",
                          `treatment_is_primary`: String = "Yes",
                          `treatment_intent`: String = "Curative",
                          `treatment_response`: String = "Not applicable",
                          `medication_name`: Option[String] = None,
                          `medication_code`: Option[String] = None,
                          `medication_class`: Option[String] = None,
                          `medication_start_date`: Option[String] = None,
                          `medication_end_date`: Option[String] = None)

